### ISSUE TITLE
Heroku site is down

### ISSUE THREAD

**Issue by webknjaz** [bocharsky-bw/stand-with-ukraine-bundle#13]
I suppose that's because there's no free plan there anymore. Consider moving whatever it was hosting to a static GH Pages based website and dropping the link from the repo frontpage sidebar?

**Comment by bocharsky-bw** [comment]
Yeah, I think we just need to drop that Heroku section completely. Would you like to open a PR? Otherwise I can do it myself

**Comment by webknjaz** [comment]
The link is in the GH UI, I can't edit that. But also, feel free to clean up the README yourself, I won't be able to send a PR anytime soon.

**Comment by bocharsky-bw** [comment]
Thanks!
