### ISSUE TITLE
Call for clarification

### ISSUE THREAD

**Issue by webknjaz** [bocharsky-bw/stand-with-ukraine-bundle#14]
Symfony used to say they stand with Ukraine but recently started switching sides silently: https://github.com/symfony/symfony/pull/53238 / https://github.com/vshymanskyy/StandWithUkraine/issues/262.

Was this the bundle they were using on their official website? If not, maybe it's worth clarifying that it's separate.

**Comment by bocharsky-bw** [comment]
No, it's a completely separate bundle, that's why I don't see any point in any clarification
